name: Daily CSV Scraper

on:
  schedule:
    # Run hourly from 8am to 6pm EST (13-23 UTC) every day
    # Add 5 to EST to get UTC
    - cron: '0 13-23 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          playwright install chromium
      
      - name: Run scraper
        run: python run_scraper.py
      
      - name: Archive CSV files
        uses: actions/upload-artifact@v4
        with:
          name: csv-data
          path: |
            maine-2025-priority-bills.csv
            archive/*.csv
          retention-days: 90
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add maine-2025-priority-bills.csv archive/*.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update: $(date +'%Y-%m-%d')" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
